### PR TITLE
Update to CSSOM 0.2.6

### PR DESCRIPTION
**Pull request by Munter**
Relates to https://github.com/One-com/assetgraph/issues/124

### CODE REVIEW

**Comment by papandreou** [comment]
Merged this and released 0.2.6-patch1.

When I try to update assetgraph to it I get a bunch of test failures, though:

```
andreas@andreas-ThinkPad-T500:~/work/assetgraph$ vows
···· ····· ························································ ················ ·················· ····· ······ ········ ········· ···· ············ ···· ······ ······· ········ ······ ···· ·································· ······· · ······ · ····· ······ ···· ···· ·············· ········ ···· ·············· ···· ·· ······ ········ ·· ······ ········ ··························· ···· ······· ·················· ·· ················ ··· ···· ··· ··············· ························································· ···· ·· ········· ··· ······················································· ················· ···· ····· ····· ························ ··········································· ··· ·· · ········· ···· ········ ········ ····· ···· ·········· ····· ······· · ········ ····· ··············· ···· ················· ····················· ··········· ···· ······· ······ ··················· ························ ·· ·· ················· ···· ····· ····· ····  
  ✓ OK » 896 honored (23.435s) 
andreas@andreas-ThinkPad-T500:~/work/assetgraph$ npm install cssom-papandreou@0.2.6patch1
npm http GET https://registry.npmjs.org/cssom-papandreou/0.2.6patch1
npm http 200 https://registry.npmjs.org/cssom-papandreou/0.2.6patch1
npm http GET https://registry.npmjs.org/cssom-papandreou/-/cssom-papandreou-0.2.6-patch1.tgz
npm http 200 https://registry.npmjs.org/cssom-papandreou/-/cssom-papandreou-0.2.6-patch1.tgz
cssom-papandreou@0.2.6-patch1 node_modules/cssom-papandreou
andreas@andreas-ThinkPad-T500:~/work/assetgraph$ vows
···· ····· ························································ ················ ·················· ····· ······ ·✗✗✗···· ········· ···· ············ ···· ······ ······· ········ ······ ···· ·································· ······· · ······ · ····· ······ ···· ···· ········✗····· ·······✗ ···· ·············· ···· ·· ······ ········ ·· ······ ········ ··························· ···· ······· ·················· ·· ················ ··· ···· ··· ··············· ························································· ···· ·· ········· ··· ······················································· ················· ···· ····· ····· ························ ··········································· ··· ·· · ········· ···· ········ ········ ····· ···· ·········· ····· ······· · ········ ····· ··············· ···· ················· ····················· ··········· ···· ······· ······ ··················· ························ ·· ·· ················· ···· ····· ····· ····  


    After loading test case with multiple src properties in one rule and multiple urls in one value 
      ✗ the graph should contain 6 CssFontFaceSrc relations 
        » expected 6, 
    got  0 (==) // CssFontFaceSrc-test.js:49 

    After loading test case with multiple src properties in one rule and multiple urls in one value then change the url of the true type font 
      ✗ the href of the incoming relation should be updated 
      TypeError: Object TypeError: Cannot set property 'url' of undefined has no method 'findRelations' 
      at Object.vows.describe.addBatch.After loading test case with multiple src properties in one rule and multiple urls in one value.then change the url of the true type font.the href of the incoming relation should be updated (/home/andreas/work/assetgraph/test/CssFontFaceSrc-test.js:57:41) 
      at runTest (/home/andreas/work/assetgraph/node_modules/vows/lib/vows.js:132:26) 
      at EventEmitter.<anonymous> (/home/andreas/work/assetgraph/node_modules/vows/lib/vows.js:78:9) 
      at EventEmitter.emit (events.js:115:20) 
      at EventEmitter.vows.describe.options.Emitter.emit (/home/andreas/work/assetgraph/node_modules/vows/lib/vows.js:237:24) 
      at Suite.runBatch.topic (/home/andreas/work/assetgraph/node_modules/vows/lib/vows/suite.js:169:45) 
      at process.startup.processNextTick.process._tickCallback (node.js:244:9) 

      ✗ the url tokens should still come in the right order 
      TypeError: Object TypeError: Cannot set property 'url' of undefined has no method 'findAssets' 
      at Object.vows.describe.addBatch.After loading test case with multiple src properties in one rule and multiple urls in one value.then change the url of the true type font.the url tokens should still come in the right order (/home/andreas/work/assetgraph/test/CssFontFaceSrc-test.js:60:45) 
      at runTest (/home/andreas/work/assetgraph/node_modules/vows/lib/vows.js:132:26) 
      at EventEmitter.<anonymous> (/home/andreas/work/assetgraph/node_modules/vows/lib/vows.js:78:9) 
      at EventEmitter.emit (events.js:115:20) 
      at EventEmitter.vows.describe.options.Emitter.emit (/home/andreas/work/assetgraph/node_modules/vows/lib/vows.js:237:24) 
      at Suite.runBatch.topic (/home/andreas/work/assetgraph/node_modules/vows/lib/vows/suite.js:169:45) 
      at process.startup.processNextTick.process._tickCallback (node.js:244:9) 

    After loading a test case with the ACE editor 
      ✗ the graph should contain 76 assets 
        » expected 76, 
    got  67 (==) // JavaScriptRequireJsCommonJsCompatibilityRequire-test.js:110 

    After loading test case then inlining the image then add a property to the second Css and mark it dirty 
      ✗ the Html should still contain both "foo" declarations 
      TypeError: Object TypeError: Cannot read property 'style' of undefined has no method 'findAssets' 
      at Object.vows.describe.addBatch.After loading test case.then inlining the image.then add a property to the second Css and mark it dirty.the Html should still contain both "foo" declarations (/home/andreas/work/assetgraph/test/HtmlStyleAttribute-test.js:56:47) 
      at runTest (/home/andreas/work/assetgraph/node_modules/vows/lib/vows.js:132:26) 
      at EventEmitter.<anonymous> (/home/andreas/work/assetgraph/node_modules/vows/lib/vows.js:78:9) 
      at EventEmitter.emit (events.js:115:20) 
      at EventEmitter.vows.describe.options.Emitter.emit (/home/andreas/work/assetgraph/node_modules/vows/lib/vows.js:237:24) 
      at Suite.runBatch.topic (/home/andreas/work/assetgraph/node_modules/vows/lib/vows/suite.js:169:45) 
      at process.startup.processNextTick.process._tickCallback (node.js:244:9) 
  ✗ Errored » 891 honored ∙ 2 broken ∙ 3 errored (24.670s) 
  andreas@andreas-ThinkPad-T500:~/work/assetgraph$ 

```

Haven't looked further into it. Any clue what might be going on?

**Comment by Munter** [comment]
Hmm, I didn't see those. I was pretty sure I ran with the linked library. Must have been mistaken. I guess this need another pass then

**Comment by papandreou** [comment]
I guess you need to run `npm link` while you've checked out the `cssom-papandreou` branch. Otherwise it'll register itself as `cssom` rather than  `cssom-papandreou`, which assetgraph is `require`ing.

**Comment by Munter** [comment]
Yes, that seems to be the mistake I made. Now I get the errors you see as well. So I guess One-com/assetgraph#124 has to wait a while

**Comment by Munter** [comment]
Ok, I've been putting some time into trying to find a proper merge point from the origin project to get 30c066c merged into your fork, but I've failed miserably every time. I simply can't figure out why the changes before that commit break so many of our test cases. I would have expected patch releases to be more stable than that.

What I have done instead is cherry pick 30c066c on top of cssom-papandreou and then it works and none of our assetgraph test cases fail. I recommend force pushing to undo the original merge and then cherry picking this specific commit just to get moving again

**Comment by papandreou** [comment]
All right, I trust you :)

You're already a collaborator in this repo, and I just made you an owner of the `cssom-papandreou` package.

**Pull request merged**
