### PR TITLE
Pull in DocumentRule implementation from upstream

### PR DESCRIPTION
**Pull request by Munter**
I need this to use assetgraph at work

### CODE REVIEW

**Comment by papandreou** [comment]
LGTM.

**Comment by papandreou** [comment]
Released cssom-papandreou 0.2.4-patch6, and updated assetgraph to it in f426937 so it'll be part of the next release.

**Comment by Munter** [comment]
Thanks

**Comment by papandreou** [comment]
It's out in assetgraph-builder 1.8.62 (assetgraph 1.6.41).

**Comment by Munter** [comment]
Yay!

**Pull request merged**
